<?php

return [
    'grant_purposes' => [
        'Mendukung program pembangunan nasional',
        'Mendukung tugas dan fungsi Polri',
        'Mendukung penanggulangan bencana alam',
        'Bantuan kemanusiaan',
        'Bantuan lainnya sesuai dengan ketentuan dan peraturan yang berlaku',
    ],

    'donor_origins' => [
        'DALAM NEGERI',
        'LUAR NEGERI',
    ],

    'countries' => [
        'AFGHANISTAN',
        'ALBANIA',
        'ALGERIA',
        'ANDORRA',
        'ANGOLA',
        'ARGENTINA',
        'ARMENIA',
        'AUSTRALIA',
        'AUSTRIA',
        'AZERBAIJAN',
        'BAHAMAS',
        'BAHRAIN',
        'BANGLADESH',
        'BARBADOS',
        'BELARUS',
        'BELGIUM',
        'BELIZE',
        'BENIN',
        'BHUTAN',
        'BOLIVIA',
        'BOSNIA AND HERZEGOVINA',
        'BOTSWANA',
        'BRAZIL',
        'BRUNEI',
        'BULGARIA',
        'BURKINA FASO',
        'BURUNDI',
        'CABO VERDE',
        'CAMBODIA',
        'CAMEROON',
        'CANADA',
        'CENTRAL AFRICAN REPUBLIC',
        'CHAD',
        'CHILE',
        'CHINA',
        'COLOMBIA',
        'COMOROS',
        'CONGO, DEMOCRATIC REPUBLIC OF THE',
        'CONGO, REPUBLIC OF THE',
        'COSTA RICA',
        'CROATIA',
        'CUBA',
        'CYPRUS',
        'CZECH REPUBLIC',
        'DENMARK',
        'DJIBOUTI',
        'DOMINICA',
        'DOMINICAN REPUBLIC',
        'ECUADOR',
        'EGYPT',
        'EL SALVADOR',
        'EQUATORIAL GUINEA',
        'ERITREA',
        'ESTONIA',
        'ESWATINI',
        'ETHIOPIA',
        'FIJI',
        'FINLAND',
        'FRANCE',
        'GABON',
        'GAMBIA',
        'GEORGIA',
        'GERMANY',
        'GHANA',
        'GREECE',
        'GRENADA',
        'GUATEMALA',
        'GUINEA',
        'GUINEA-BISSAU',
        'GUYANA',
        'HAITI',
        'HONDURAS',
        'HUNGARY',
        'ICELAND',
        'INDIA',
        'INDONESIA',
        'IRAN',
        'IRAQ',
        'IRELAND',
        'ISRAEL',
        'ITALY',
        'JAMAICA',
        'JAPAN',
        'JORDAN',
        'KAZAKHSTAN',
        'KENYA',
        'KIRIBATI',
        'KUWAIT',
        'KYRGYZSTAN',
        'LAOS',
        'LATVIA',
        'LEBANON',
        'LESOTHO',
        'LIBERIA',
        'LIBYA',
        'LIECHTENSTEIN',
        'LITHUANIA',
        'LUXEMBOURG',
        'MADAGASCAR',
        'MALAWI',
        'MALAYSIA',
        'MALDIVES',
        'MALI',
        'MALTA',
        'MARSHALL ISLANDS',
        'MAURITANIA',
        'MAURITIUS',
        'MEXICO',
        'MICRONESIA',
        'MOLDOVA',
        'MONACO',
        'MONGOLIA',
        'MONTENEGRO',
        'MOROCCO',
        'MOZAMBIQUE',
        'MYANMAR',
        'NAMIBIA',
        'NAURU',
        'NEPAL',
        'NETHERLANDS',
        'NEW ZEALAND',
        'NICARAGUA',
        'NIGER',
        'NIGERIA',
        'NORTH KOREA',
        'NORTH MACEDONIA',
        'NORWAY',
        'OMAN',
        'PAKISTAN',
        'PALAU',
        'PANAMA',
        'PAPUA NEW GUINEA',
        'PARAGUAY',
        'PERU',
        'PHILIPPINES',
        'POLAND',
        'PORTUGAL',
        'QATAR',
        'ROMANIA',
        'RUSSIA',
        'RWANDA',
        'SAINT KITTS AND NEVIS',
        'SAINT LUCIA',
        'SAINT VINCENT AND THE GRENADINES',
        'SAMOA',
        'SAN MARINO',
        'SAO TOME AND PRINCIPE',
        'SAUDI ARABIA',
        'SENEGAL',
        'SERBIA',
        'SEYCHELLES',
        'SIERRA LEONE',
        'SINGAPORE',
        'SLOVAKIA',
        'SLOVENIA',
        'SOLOMON ISLANDS',
        'SOMALIA',
        'SOUTH AFRICA',
        'SOUTH KOREA',
        'SOUTH SUDAN',
        'SPAIN',
        'SRI LANKA',
        'SUDAN',
        'SURINAME',
        'SWEDEN',
        'SWITZERLAND',
        'SYRIA',
        'TAIWAN',
        'TAJIKISTAN',
        'TANZANIA',
        'THAILAND',
        'TIMOR-LESTE',
        'TOGO',
        'TONGA',
        'TRINIDAD AND TOBAGO',
        'TUNISIA',
        'TURKEY',
        'TURKMENISTAN',
        'TUVALU',
        'UGANDA',
        'UKRAINE',
        'UNITED ARAB EMIRATES',
        'UNITED KINGDOM',
        'UNITED STATES',
        'URUGUAY',
        'UZBEKISTAN',
        'VANUATU',
        'VATICAN CITY',
        'VENEZUELA',
        'VIETNAM',
        'YEMEN',
        'ZAMBIA',
        'ZIMBABWE',
    ],
];
